import {projects} from './projects.mjs';
import {piecePath} from './geometry.mjs';
const t=(lang,tr,en)=>lang==='en'?en:tr;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(v,l)=>v[l==='en'?1:0];
export const puzzleMark=()=>'<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M5 5h10c-4-8 14-8 10 0h10v10c8-4 8 14 0 10v10H25c4-8-14-8-10 0H5V25c8 4 8-14 0-10Z" fill="currentColor"/></svg>';
export function boxLid(p,lang,base='') {return `<div class="box-solid" style="--box-color:${p.color}"><div class="box-bottom-edge" aria-hidden="true">${p.number} / SEVDE NUR FIDAN <span>${pick(p.category,lang)}</span></div><div class="box-right-edge" aria-hidden="true">${p.number} — ${t(lang,'PARÇALAR & MEKÂNLAR','PIECES & PLACES')}</div><div class="box-lid"><div class="box-title-band"><span>${p.number}</span><h3>${esc(pick(p.title,lang))}</h3></div><div class="box-artwork"><img src="${base+p.image}" alt="${esc(pick(p.alt,lang))}" loading="lazy" draggable="false"></div><div class="box-print-band"><div class="box-brand">${puzzleMark()}<span>SEVDE<br>NUR FIDAN</span></div><span class="box-edition">${esc(pick(p.label,lang))}</span><span class="box-pieces"><b>${p.pieceCount}</b> ${t(lang,'PARÇA','PIECES')}</span></div></div></div>`;}
export function puzzleBox(p,lang){return `<article class="project-package" id="package-${p.id}" style="--folder:${p.color};--tilt:${+p.number%2?-2:2}deg" data-project="${p.id}"><a class="package-cover" href="${p.route}" data-open="${p.id}" aria-label="${t(lang,'Yapboz kutusunu aç:','Open puzzle box:')} ${esc(pick(p.title,lang))}">${boxLid(p,lang)}</a><div class="package-foot"><span class="package-status" data-status="${p.id}">${t(lang,'Bir araya getir','Bring it together')}</span><a class="package-action package-action-primary" href="${p.route}">${t(lang,'Projeyi keşfet','Explore project')} <span aria-hidden="true">↗</span></a><a class="package-action package-action-secondary" href="${p.route}" data-open="${p.id}" data-replay="true">${t(lang,'Yapbozu aç','Open puzzle')} ${puzzleMark()}</a></div></article>`;}
export function collectionTools(lang){return `<div class="collection-tools" role="group" aria-label="${t(lang,'Koleksiyon görünümü','Collection view')}"><button data-collection-view="boxes" aria-pressed="true">${t(lang,'Kutular','Boxes')}</button><button data-collection-view="index" aria-pressed="false">${t(lang,'Dizin','Index')}</button></div><p class="collection-help">${t(lang,'Kutuları sürükle veya oklarla gez. Bir kutu aç, içindeki dünyayı keşfet.','Drag the shelf or use the arrows. Open a box and discover the world inside.')}</p>`;}
export function sketchPortrait(lang){const pieces=Array.from({length:9},(_,i)=>{const path=piecePath(i%3,Math.floor(i/3),3,3,600,800);return `<g class="portrait-fragment"><defs><clipPath id="portrait-${i}"><path d="${path}"/></clipPath></defs><image href="assets/sketches/landscape-assembly.webp" width="600" height="800" preserveAspectRatio="none" clip-path="url(#portrait-${i})"/><path d="${path}" fill="none" stroke="#eee7da" stroke-width="1.3"/></g>`;}).join('');return `<svg class="portrait-assembly" viewBox="0 0 600 800" role="img" aria-label="${t(lang,'Sevde’nin yapboz profil eskizi','Sevde’s jigsaw profile sketch')}">${pieces}</svg><button class="portrait-replay">${t(lang,'Parçaları yeniden birleştir','Reconnect the pieces')} ↺</button>`;}
export function caseFacts(p,lang){return `<div class="case-facts"><div><span>${t(lang,'Koleksiyon','Collection')}</span><strong>${p.number} / 07</strong></div><div><span>${t(lang,'Çalışma alanı','Focus')}</span><strong>${esc(pick(p.label,lang))}</strong></div><div><span>${t(lang,'Arşiv','Archive')}</span><strong>${p.pages.length} ${t(lang,'orijinal pafta','original boards')}</strong></div><a href="#drawings">${t(lang,'Çizimlere göz at','Browse the drawings')} ↘</a></div>`;}
