import {projects} from './projects.mjs';
export function setupBoxes({motion}){
 const abort=new AbortController(),opts={signal:abort.signal};let portraitTween,observer;
 const rail=document.querySelector('.packages'),cards=[...document.querySelectorAll('.project-package')];let active=0,frame,resize,drag,suppressClick=false,releaseTimer,backdrop;
 if(rail){
  const en=document.documentElement.lang==='en';rail.tabIndex=0;rail.setAttribute('role','region');rail.setAttribute('aria-roledescription','carousel');rail.setAttribute('aria-label',en?'Project puzzle boxes':'Proje yapboz kutuları');rail.dataset.lenisPrevent='';
  const controls=document.createElement('div');controls.className='carousel-controls';controls.innerHTML=`<button class="carousel-prev" aria-label="${en?'Previous box':'Önceki kutu'}">←</button><span class="carousel-position" aria-live="polite"></span><button class="carousel-next" aria-label="${en?'Next box':'Sonraki kutu'}">→</button>`;rail.after(controls);
  const prev=controls.querySelector('.carousel-prev'),next=controls.querySelector('.carousel-next'),status=controls.querySelector('.carousel-position');
  const shelf=document.querySelector('.collection');backdrop=document.createElement('div');backdrop.className='shelf-backdrop';backdrop.setAttribute('aria-hidden','true');shelf.prepend(backdrop);
  let lastProject='';
  const atmosphere=()=>{const p=projects[active];if(!p||lastProject===p.id)return;lastProject=p.id;shelf.style.setProperty('--shelf-color',p.color);const layer=document.createElement('div');layer.style.backgroundImage=`url("${p.puzzleImage}")`;backdrop.append(layer);requestAnimationFrame(()=>layer.classList.add('shown'));while(backdrop.children.length>2)backdrop.firstElementChild.remove();if(layer.previousElementSibling)layer.previousElementSibling.classList.remove('shown');try{sessionStorage.setItem('portfolio-selected-box',p.id);}catch{}};
  const paint=()=>{frame=null;if(document.querySelector('.collection').classList.contains('index-view'))return;const center=rail.getBoundingClientRect().left+rail.clientWidth/2;let nearest=Infinity;cards.forEach((card,i)=>{const r=card.getBoundingClientRect(),distance=Math.abs(r.left+r.width/2-center);if(distance<nearest){nearest=distance;active=i;}});cards.forEach((card,i)=>card.classList.toggle('is-current',i===active));status.textContent=`${String(active+1).padStart(2,'0')} / ${String(cards.length).padStart(2,'0')}`;prev.disabled=active===0;next.disabled=active===cards.length-1;};
  const go=(index,instant=false)=>{const card=cards[Math.max(0,Math.min(cards.length-1,index))],r=card.getBoundingClientRect(),rr=rail.getBoundingClientRect();rail.scrollTo({left:rail.scrollLeft+r.left-rr.left-(rail.clientWidth-r.width)/2,behavior:motion()&&!instant?'smooth':'instant'});};
  prev.addEventListener('click',()=>go(active-1),opts);next.addEventListener('click',()=>go(active+1),opts);
  rail.addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(()=>{paint();atmosphere();});},{...opts,passive:true});
  rail.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0||shelf.classList.contains('index-view'))return;drag={id:e.pointerId,x:e.clientX,left:rail.scrollLeft,moved:false};suppressClick=false;},opts);
  rail.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const delta=e.clientX-drag.x;if(!drag.moved&&Math.abs(delta)>7){drag.moved=true;rail.setPointerCapture(e.pointerId);rail.classList.add('is-dragging');document.querySelector('.cursor')?.classList.remove('visible');}if(drag.moved){e.preventDefault();rail.scrollLeft=drag.left-delta;}},opts);
  const release=e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;rail.classList.remove('is-dragging');if(rail.hasPointerCapture(e.pointerId))rail.releasePointerCapture(e.pointerId);if(moved){suppressClick=true;paint();go(active);clearTimeout(releaseTimer);releaseTimer=setTimeout(()=>suppressClick=false,350);}};
  rail.addEventListener('pointerup',release,opts);rail.addEventListener('pointercancel',release,opts);
  window.addEventListener('pointerup',release,opts);window.addEventListener('pointercancel',release,opts);
  rail.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},{...opts,capture:true});
  rail.addEventListener('dragstart',e=>e.preventDefault(),opts);
  rail.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||document.querySelector('.collection').classList.contains('index-view'))return;e.preventDefault();go(e.key==='Home'?0:e.key==='End'?cards.length-1:active+(e.key==='ArrowRight'?1:-1));},opts);
  rail.addEventListener('focusin',e=>{const card=e.target.closest('.project-package');if(card&&!document.querySelector('.collection').classList.contains('index-view'))go(cards.indexOf(card));},opts);
  resize=new ResizeObserver(()=>{go(active,true);paint();atmosphere();});resize.observe(rail);
  document.querySelectorAll('[data-collection-view]').forEach(b=>b.addEventListener('click',()=>requestAnimationFrame(()=>{go(active);paint();}),opts));
  try{const saved=cards.findIndex(card=>card.dataset.project===sessionStorage.getItem('portfolio-selected-box'));if(saved>=0)active=saved;}catch{}
  const hashCard=cards.findIndex(card=>'#'+card.id===location.hash);if(hashCard>=0)active=hashCard;const initial=active;requestAnimationFrame(()=>{go(initial,true);paint();atmosphere();});
 }
 document.querySelectorAll('.package-cover,.hero-art').forEach(el=>{const box=el.querySelector('.box-solid');if(!box)return;el.addEventListener('pointermove',e=>{if(!motion()||e.pointerType==='touch'||document.querySelector('.collection')?.classList.contains('index-view'))return;const r=el.getBoundingClientRect();box.style.setProperty('--rx',`${24-(e.clientY-r.top)/r.height*10}deg`);box.style.setProperty('--ry',`${-24+(e.clientX-r.left)/r.width*14}deg`);},opts);el.addEventListener('pointerleave',()=>{box.style.removeProperty('--rx');box.style.removeProperty('--ry');},opts);});
 const collection=document.querySelector('.collection');document.querySelectorAll('[data-collection-view]').forEach(button=>button.addEventListener('click',()=>{collection.classList.toggle('index-view',button.dataset.collectionView==='index');document.querySelectorAll('[data-collection-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));requestAnimationFrame(()=>window.ScrollTrigger?.refresh());},opts));
 const fragments=[...document.querySelectorAll('.portrait-fragment')];
 const assemble=()=>{portraitTween?.kill();if(!fragments.length)return;if(!motion()){gsap.set(fragments,{clearProps:'all'});return;}portraitTween=gsap.fromTo(fragments,{x:i=>(i%3-1)*70,y:i=>(Math.floor(i/3)-1)*70,rotation:i=>(i%3-1)*12,opacity:.2},{x:0,y:0,rotation:0,opacity:1,stagger:.075,duration:1.25,ease:'power3.out'});};
 if(fragments.length){observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){assemble();observer.disconnect();}},{threshold:.25});observer.observe(document.querySelector('.portrait-assembly'));document.querySelector('.portrait-replay').addEventListener('click',assemble,opts);}
 window.addEventListener('portfolio-motion',()=>{if(!motion()){portraitTween?.kill();gsap.set(fragments,{clearProps:'all'});document.querySelectorAll('.box-solid').forEach(b=>{b.style.removeProperty('--rx');b.style.removeProperty('--ry');});}},opts);
 return ()=>{abort.abort();portraitTween?.kill();observer?.disconnect();resize?.disconnect();cancelAnimationFrame(frame);clearTimeout(releaseTimer);backdrop?.remove();document.querySelector('.carousel-controls')?.remove();};
}
